# /Users/user/Documents/Docker/logstash/logstash.conf

input {
  tcp {
    port => 5044          # 開放 50xx port 接收日誌
    codec => json_lines   # 預期接收 JSON 格式的日誌
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"] # 送到 Elasticsearch 容器
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
  # 同時在終端機印出日誌，方便除錯
  stdout { codec => rubydebug }
}